# Generated by Django 4.2.4 on 2024-09-08 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="cs0000",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dosyaBaslik", models.CharField(max_length=6)),
                ("versiyonNumarasi", models.CharField(max_length=2)),
                ("uyeKodu", models.CharField(max_length=5)),
                ("portfoyKodu", models.CharField(max_length=3)),
                ("rezerveAlan", models.CharField(max_length=62)),
                ("uyeAdi", models.CharField(max_length=30)),
                ("olusturmaTarihi", models.CharField(max_length=8)),
                ("bildirimTarihi", models.CharField(max_length=8)),
                ("rezerveAlan2", models.CharField(max_length=376)),
            ],
        ),
    ]
