# Generated by Django 4.2.4 on 2024-09-17 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ParsingApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="rawData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.CharField(max_length=1000)),
            ],
        ),
    ]
