# Generated by Django 4.2.4 on 2024-09-24 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ParsingApp", "0022_rmkrskonutcs0000"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RMKRSKONUTCS0301",
        ),
    ]
