# Generated by Django 4.2.4 on 2024-09-25 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ParsingApp", "0023_delete_rmkrskonutcs0301"),
    ]

    operations = [
        migrations.CreateModel(
            name="RMKRSKONUTCS0301",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Versiyon Numarası", models.CharField(max_length=255)),
                ("Üye Kodu", models.CharField(max_length=255)),
                ("Portföy Kodu", models.CharField(max_length=255)),
                ("Portföy Alt Kodu", models.CharField(max_length=255)),
                ("Müşteri Hesap Numarası", models.CharField(max_length=255)),
                ("Hesap Sahibinin Numarası", models.CharField(max_length=255)),
                ("Özel Talimat Göstergesi", models.CharField(max_length=255)),
                ("Adres Tipi", models.CharField(max_length=255)),
                ("Şimdiki/Önceki Adres Göstergesi", models.CharField(max_length=255)),
                ("Adrese Taşındığı Tarih", models.CharField(max_length=255)),
                ("Adresten Ayrıldığı Tarih", models.CharField(max_length=255)),
                ("Adreste Kaldığı Süre", models.CharField(max_length=255)),
                ("Adres Satırı 1", models.CharField(max_length=255)),
                ("Adres Satırı 2", models.CharField(max_length=255)),
                ("Adres Satırı 3", models.CharField(max_length=255)),
                ("Adres Satırı 4", models.CharField(max_length=255)),
                ("Posta Kodu", models.CharField(max_length=255)),
                ("Rezerve Alan", models.CharField(max_length=255)),
            ],
        ),
    ]
