# Generated by Django 4.2.4 on 2024-09-25 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ParsingApp", "0024_rmkrskonutcs0301"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RMKRSKONUTCS0000",
        ),
    ]
