# Generated by Django 4.2.4 on 2024-09-26 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ParsingApp", "0032_rmkrskonutcs0000"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RMKRSKONUTCS0000",
        ),
    ]
